spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager
    username: your_db_user
    password: your_db_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  security:
    jwt:
      secret-key: YOUR_SECRET_KEY
      expiration: 36000000
